import { learningModules } from "@/lib/learning-materials";

export { learningModules };

export const promoSlides = [
  {
    title: "Harga Early Bird Masih Tersedia",
    desc: "Paket Belajar mulai Rp 25.000 — harga naik setelah 500 slot habis.",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=1200&auto=format&fit=crop",
  },
  {
    title: "Tryout UM PTKIN 2026 Sudah Hadir",
    desc: "5 paket soal HOTS khusus UM-PTKIN. Mulai latihan sekarang.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1200&auto=format&fit=crop",
  },
  {
    title: "SIMAK UI Segera Dibuka",
    desc: "Siapkan strategi dan mulai simulasi dari sekarang.",
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?q=80&w=1200&auto=format&fit=crop",
  },
];

export const ptnDeadlines = [
  {
    id: "itb",
    name: "Institut Teknologi Bandung",
    shortName: "SSU ITB",
    selectionName: "Seleksi Siswa Unggul ITB 2026",
    city: "Bandung",
    openAt: "2 Apr 2026",
    closeAt: "3 Mei 2026",
    examAt: "Bertahap sesuai jalur",
    resultAt: "26 Mei 2026",
    status: "Perlu Cek Berkala",
    color: "bg-blue-100 text-blue-700",
    priority: "Tinggi",
    fee: "Rp750.000; gratis untuk KIP-K/3T sesuai ketentuan",
    scheme: "Tes dan non-tes; peserta yang sudah diterima SNBP/SNBT tidak dapat dinyatakan lulus SSU.",
    materials: "Penalaran, kemampuan akademik, dan evaluasi sesuai jalur pilihan.",
    documents: ["Email aktif", "NISN", "Data sekolah", "Dokumen identitas", "Bukti prestasi bila memilih jalur prestasi"],
    strategy: "Cek email dan portal admisi rutin karena notifikasi proses seleksi dikirim berkala.",
    sourceUrl: "https://admission.itb.ac.id/ssu",
    sourceLabel: "Admission ITB",
  },
  {
    id: "ui",
    name: "Universitas Indonesia",
    shortName: "SIMAK UI",
    selectionName: "SIMAK UI S1 Reguler & Vokasi 2026",
    city: "Depok",
    openAt: "8 Mei 2026",
    closeAt: "5 Jun 2026",
    examAt: "14 Jun 2026",
    resultAt: "Paling lambat 1 Jul 2026",
    status: "Pendaftaran Buka",
    color: "bg-emerald-100 text-emerald-700",
    priority: "Sangat Tinggi",
    fee: "S1 & Vokasi Rp650.000; KKI Rp1.800.000; RPL Rp900.000",
    scheme: "Ujian mandiri terpadu untuk Vokasi, S1 Reguler, KKI, RPL, dan jenjang lanjut.",
    materials: "Kemampuan dasar, literasi, penalaran, dan materi sesuai kelompok program.",
    documents: ["Akun pendaftaran UI", "Data diri dan pendidikan", "Pilihan program studi", "Bukti pembayaran"],
    strategy: "Prioritaskan latihan Matematika Dasar, Bahasa Indonesia, Bahasa Inggris, dan penalaran berbasis waktu.",
    sourceUrl: "https://simak.ui.ac.id/simak-ui/",
    sourceLabel: "SIMAK UI",
  },
  {
    id: "ugm",
    name: "Universitas Gadjah Mada",
    shortName: "UM UGM CBT",
    selectionName: "UM UGM Computer Based Test 2026",
    city: "Yogyakarta/Jakarta",
    openAt: "14 Apr 2026",
    closeAt: "5 Mei 2026",
    examAt: "2-6 Jun 2026",
    resultAt: "12 Jun 2026",
    status: "Pendaftaran Selesai",
    color: "bg-slate-100 text-slate-700",
    priority: "Tinggi",
    fee: "Yogyakarta Rp350.000; Jakarta Rp550.000",
    scheme: "Kombinasi skor UM UGM CBT dan skor UTBK-SNBT 2026.",
    materials: "Tes Kemampuan Dasar Umum, Tes Potensi, dan Tes Kemampuan Akademik sesuai prodi.",
    documents: ["Ijazah/SKL", "Kartu peserta UTBK-SNBT 2026", "Identitas berfoto", "Akun pendaftaran UGM"],
    strategy: "Pastikan skor UTBK tersedia; latihan harus menggabungkan TPS dan TKA sesuai prodi tujuan.",
    sourceUrl: "https://um.ugm.ac.id/um-ugm-computer-based-test-um-ugm-cbt-2026/",
    sourceLabel: "UM UGM",
  },
  {
    id: "unpad",
    name: "Universitas Padjadjaran",
    shortName: "SMUP UNPAD",
    selectionName: "SMUP Mandiri Unpad 2026",
    city: "Bandung/Jatinangor",
    openAt: "1 Apr 2026",
    closeAt: "2 Jun 2026",
    examAt: "Sesuai jalur pilihan",
    resultAt: "Cek portal SMUP",
    status: "Pendaftaran Buka",
    color: "bg-emerald-100 text-emerald-700",
    priority: "Tinggi",
    fee: "Cek portal SMUP sesuai jalur dan program studi",
    scheme: "Prestasi akademik, minat dan bakat, kelas internasional, dan kemitraan strategis.",
    materials: "Administrasi, portofolio/prestasi, dan evaluasi sesuai skema jalur.",
    documents: ["Data diri", "Data sekolah", "Rapor/prestasi", "Dokumen pendukung jalur pilihan"],
    strategy: "Pilih jalur berdasarkan kekuatan terbesar: nilai, prestasi, minat bakat, atau kelas internasional.",
    sourceUrl: "https://fk.unpad.ac.id/smup-mandiri-unpad-2026/",
    sourceLabel: "Info SMUP Unpad",
  },
  {
    id: "its",
    name: "Institut Teknologi Sepuluh Nopember",
    shortName: "SMITS",
    selectionName: "Seleksi Mandiri ITS 2026",
    city: "Surabaya",
    openAt: "14 Apr 2026",
    closeAt: "8 Mei 2026 / 3 Jun 2026",
    examAt: "SMITS ACE luring di ITS",
    resultAt: "26 Mei 2026 / 1 Jul 2026",
    status: "Bertahap",
    color: "bg-blue-100 text-blue-700",
    priority: "Menengah-Tinggi",
    fee: "Cek portal admisi ITS sesuai jalur",
    scheme: "SMITS FLAT untuk talenta/prestasi dan SMITS ACE untuk jalur tes.",
    materials: "Tes SMITS untuk ACE; penilaian prestasi/rapor untuk FLAT.",
    documents: ["Akun myITS Admission", "Data sekolah", "Bukti prestasi/rapor", "Dokumen pembayaran"],
    strategy: "Jika kuat prestasi pilih FLAT; jika mengandalkan tes akademik siapkan ACE lebih intensif.",
    sourceUrl: "https://admission.its.ac.id/beranda/jalur",
    sourceLabel: "myITS Admission",
  },
  {
    id: "ipb",
    name: "IPB University",
    shortName: "SM-IPB",
    selectionName: "Seleksi Mandiri IPB 2026",
    city: "Bogor",
    openAt: "5 Mei 2026",
    closeAt: "12 Jun 2026",
    examAt: "Ujian online sesuai jadwal portal",
    resultAt: "Cek portal admisi",
    status: "Pendaftaran Buka",
    color: "bg-emerald-100 text-emerald-700",
    priority: "Menengah-Tinggi",
    fee: "Rp750.000",
    scheme: "Skor UTBK dan/atau ujian online mandiri sesuai jalur yang dipilih.",
    materials: "Tes Kemampuan Skolastik HOTS; fokus pemecahan masalah dan penalaran sains.",
    documents: ["Perangkat ujian online", "Koneksi stabil", "Smartphone pengawasan", "Akun admisi"],
    strategy: "Siapkan perangkat sejak awal; latihan soal HOTS singkat dengan tekanan waktu.",
    sourceUrl: "https://admisi.ipb.ac.id/",
    sourceLabel: "Admisi IPB",
  },
  {
    id: "ub",
    name: "Universitas Brawijaya",
    shortName: "SMUB",
    selectionName: "Seleksi Mandiri UB 2026",
    city: "Malang",
    openAt: "7 Mei 2026",
    closeAt: "28 Mei 2026",
    examAt: "Mayoritas seleksi berbasis prestasi/rapor sesuai jalur",
    resultAt: "17 Jun 2026",
    status: "Buka Segera",
    color: "bg-blue-100 text-blue-700",
    priority: "Menengah",
    fee: "Cek portal admisi UB sesuai jalur",
    scheme: "Beberapa jalur mandiri: prestasi, rapor, UTBK, dan skema khusus lain.",
    materials: "Kurasi prestasi, rapor, dan dokumen pendukung jalur.",
    documents: ["Rapor", "Sertifikat prestasi", "Identitas", "Dokumen sekolah"],
    strategy: "Pilih jalur berdasarkan bukti paling kuat; rapikan file prestasi sebelum daftar.",
    sourceUrl: "https://selma.ub.ac.id/",
    sourceLabel: "SELMA UB",
  },
  {
    id: "undip",
    name: "Universitas Diponegoro",
    shortName: "UM UNDIP",
    selectionName: "Ujian Mandiri Sarjana UNDIP 2026",
    city: "Semarang/Online",
    openAt: "5 Mei 2026",
    closeAt: "11 Jun 2026",
    examAt: "Tes tertulis berbasis komputer daring",
    resultAt: "6 Jul 2026",
    status: "Pendaftaran Buka",
    color: "bg-emerald-100 text-emerald-700",
    priority: "Tinggi",
    fee: "Cek portal PMB UNDIP sesuai kelompok prodi",
    scheme: "Seleksi mandiri sarjana dengan ujian berbasis komputer secara daring.",
    materials: "TPS, literasi, numerasi, dan materi akademik sesuai program studi.",
    documents: ["Email aktif", "Data diri", "Data orang tua", "Data pendidikan", "Bukti pembayaran"],
    strategy: "Latihan CBT online dan pastikan perangkat stabil karena ujian dilakukan daring.",
    sourceUrl: "https://pmb.undip.ac.id/sarjana/jalur-um-sarjana/",
    sourceLabel: "PMB UNDIP",
  },
  {
    id: "unair",
    name: "Universitas Airlangga",
    shortName: "SMUA",
    selectionName: "Seleksi Mandiri Universitas Airlangga 2026",
    city: "Surabaya",
    openAt: "Apr 2026",
    closeAt: "Cek portal PPMB",
    examAt: "Tes/penilaian sesuai jalur",
    resultAt: "Cek portal PPMB",
    status: "Bertahap",
    color: "bg-blue-100 text-blue-700",
    priority: "Tinggi",
    fee: "Cek PPMB UNAIR sesuai jalur",
    scheme: "Jalur mandiri dengan pilihan tes, prestasi, dan skema program tertentu.",
    materials: "Tes potensi, akademik, literasi, serta evaluasi dokumen sesuai jalur.",
    documents: ["Akun pendaftaran", "Rapor/ijazah", "Identitas", "Pilihan prodi", "Dokumen prestasi bila ada"],
    strategy: "Pisahkan strategi untuk jalur tes dan non-tes; jangan memakai satu rencana untuk semua jalur.",
    sourceUrl: "https://ppmb.unair.ac.id/",
    sourceLabel: "PPMB UNAIR",
  },
  {
    id: "uns",
    name: "Universitas Sebelas Maret",
    shortName: "SM UNS",
    selectionName: "Seleksi Mandiri UNS 2026",
    city: "Surakarta",
    openAt: "Mei 2026",
    closeAt: "Cek portal SPMB",
    examAt: "UTUL/penilaian portofolio sesuai jalur",
    resultAt: "Cek portal SPMB",
    status: "Buka Segera",
    color: "bg-blue-100 text-blue-700",
    priority: "Menengah-Tinggi",
    fee: "Cek portal SPMB UNS sesuai jalur",
    scheme: "Beberapa jalur mandiri seperti UTUL, prestasi, kemitraan, dan kelas internasional.",
    materials: "TPS, akademik dasar, dan materi sesuai kelompok saintek/soshum/campuran.",
    documents: ["Akun SPMB", "Rapor", "Ijazah/SKL", "Identitas", "Sertifikat pendukung"],
    strategy: "Jika memilih UTUL, jadwalkan simulasi penuh; jika prestasi, kuatkan bukti portofolio.",
    sourceUrl: "https://spmb.uns.ac.id/",
    sourceLabel: "SPMB UNS",
  },
  {
    id: "unnes",
    name: "Universitas Negeri Semarang",
    shortName: "SM UNNES",
    selectionName: "Seleksi Mandiri UNNES 2026",
    city: "Semarang",
    openAt: "Mei 2026",
    closeAt: "Cek portal penerimaan",
    examAt: "Tes/seleksi sesuai jalur",
    resultAt: "Cek portal penerimaan",
    status: "Buka Segera",
    color: "bg-blue-100 text-blue-700",
    priority: "Menengah",
    fee: "Cek penerimaan UNNES",
    scheme: "Seleksi mandiri sarjana dengan beberapa skema prestasi dan tes.",
    materials: "Tes potensi akademik, literasi, numerasi, dan dokumen prestasi.",
    documents: ["Akun penerimaan", "Data sekolah", "Rapor", "Identitas", "Bukti pembayaran"],
    strategy: "Cek syarat khusus prodi kependidikan dan seni/olahraga sejak awal.",
    sourceUrl: "https://penerimaan.unnes.ac.id/",
    sourceLabel: "Penerimaan UNNES",
  },
  {
    id: "uny",
    name: "Universitas Negeri Yogyakarta",
    shortName: "SM UNY",
    selectionName: "Seleksi Mandiri UNY 2026",
    city: "Yogyakarta",
    openAt: "Mei 2026",
    closeAt: "Cek portal PMB",
    examAt: "CBT/portofolio sesuai jalur",
    resultAt: "Cek portal PMB",
    status: "Bertahap",
    color: "bg-blue-100 text-blue-700",
    priority: "Menengah",
    fee: "Cek PMB UNY sesuai jalur",
    scheme: "Jalur CBT, prestasi, skor UTBK, dan portofolio sesuai ketentuan kampus.",
    materials: "TPS, literasi, numerasi, serta portofolio untuk prodi tertentu.",
    documents: ["Akun PMB", "Rapor", "Portofolio jika wajib", "Identitas", "Bukti pembayaran"],
    strategy: "Untuk prodi seni/olahraga, portofolio harus disiapkan paralel dengan latihan tes.",
    sourceUrl: "https://pmb.uny.ac.id/",
    sourceLabel: "PMB UNY",
  },
  {
    id: "upi",
    name: "Universitas Pendidikan Indonesia",
    shortName: "SM UPI",
    selectionName: "Seleksi Mandiri UPI 2026",
    city: "Bandung",
    openAt: "Mei 2026",
    closeAt: "Cek portal PMB",
    examAt: "Tes/penilaian sesuai prodi",
    resultAt: "Cek portal PMB",
    status: "Buka Segera",
    color: "bg-blue-100 text-blue-700",
    priority: "Menengah",
    fee: "Cek PMB UPI",
    scheme: "Seleksi mandiri untuk prodi pendidikan dan non-pendidikan dengan syarat prodi tertentu.",
    materials: "Tes potensi, literasi, numerasi, dan tes keterampilan untuk prodi khusus.",
    documents: ["Akun PMB", "Rapor/ijazah", "Identitas", "Portofolio/prodi khusus", "Bukti bayar"],
    strategy: "Perhatikan syarat tes keterampilan untuk prodi olahraga, seni, dan bidang khusus.",
    sourceUrl: "https://pmb.upi.edu/",
    sourceLabel: "PMB UPI",
  },
  {
    id: "unj",
    name: "Universitas Negeri Jakarta",
    shortName: "PENMABA UNJ",
    selectionName: "Penerimaan Mahasiswa Baru Mandiri UNJ 2026",
    city: "Jakarta",
    openAt: "Apr 2026",
    closeAt: "31 Mei 2026",
    examAt: "Tes/rapor sesuai jalur",
    resultAt: "Cek portal PENMABA",
    status: "Pendaftaran Buka",
    color: "bg-emerald-100 text-emerald-700",
    priority: "Menengah-Tinggi",
    fee: "Cek portal PENMABA UNJ",
    scheme: "Jalur rapor, prestasi, dan tes mandiri sesuai program studi.",
    materials: "TPS, akademik dasar, literasi, numerasi, serta portofolio untuk prodi tertentu.",
    documents: ["Akun PENMABA", "Rapor", "Identitas", "Sertifikat prestasi", "Bukti pembayaran"],
    strategy: "Karena dekat pusat kota dan peminat tinggi, siapkan pilihan prodi cadangan realistis.",
    sourceUrl: "https://penmaba.unj.ac.id/",
    sourceLabel: "PENMABA UNJ",
  },
  {
    id: "usu",
    name: "Universitas Sumatera Utara",
    shortName: "SMM USU",
    selectionName: "Seleksi Mandiri Masuk USU 2026",
    city: "Medan",
    openAt: "Mei 2026",
    closeAt: "Cek portal seleksi",
    examAt: "Tes mandiri/penilaian sesuai jalur",
    resultAt: "Cek portal seleksi",
    status: "Buka Segera",
    color: "bg-blue-100 text-blue-700",
    priority: "Menengah",
    fee: "Cek portal seleksi USU",
    scheme: "Seleksi mandiri sarjana dengan ujian dan/atau penilaian dokumen sesuai ketentuan.",
    materials: "TPS, literasi, numerasi, dan materi akademik dasar.",
    documents: ["Akun seleksi", "Ijazah/SKL", "Identitas", "Data sekolah", "Bukti pembayaran"],
    strategy: "Jaga ritme latihan numerasi dan literasi karena banyak jalur mandiri menekan waktu.",
    sourceUrl: "https://seleksi.usu.ac.id/",
    sourceLabel: "Seleksi USU",
  },
  {
    id: "unhas",
    name: "Universitas Hasanuddin",
    shortName: "JNS UNHAS",
    selectionName: "Jalur Non Subsidi Universitas Hasanuddin 2026",
    city: "Makassar",
    openAt: "Mei 2026",
    closeAt: "Cek portal PMB",
    examAt: "Tes/penilaian sesuai jalur",
    resultAt: "Cek portal PMB",
    status: "Buka Segera",
    color: "bg-blue-100 text-blue-700",
    priority: "Menengah-Tinggi",
    fee: "Cek portal PMB UNHAS",
    scheme: "Jalur mandiri/non-subsidi dengan mekanisme seleksi sesuai ketentuan universitas.",
    materials: "Tes potensi, akademik dasar, dan evaluasi dokumen.",
    documents: ["Akun PMB", "Identitas", "Ijazah/SKL", "Data sekolah", "Bukti pembayaran"],
    strategy: "Periksa syarat fakultas kesehatan lebih teliti karena biasanya punya ketentuan tambahan.",
    sourceUrl: "https://regpmb.unhas.ac.id/",
    sourceLabel: "PMB UNHAS",
  },
  {
    id: "unand",
    name: "Universitas Andalas",
    shortName: "SIMA UNAND",
    selectionName: "Seleksi Masuk Universitas Andalas 2026",
    city: "Padang",
    openAt: "Mei 2026",
    closeAt: "Cek portal PMB",
    examAt: "Tes/UTBK/prestasi sesuai jalur",
    resultAt: "Cek portal PMB",
    status: "Bertahap",
    color: "bg-blue-100 text-blue-700",
    priority: "Menengah",
    fee: "Cek PMB UNAND",
    scheme: "Jalur mandiri melalui skema akademik, prestasi, dan/atau skor UTBK sesuai pengumuman.",
    materials: "TPS, literasi, numerasi, dan penalaran akademik.",
    documents: ["Akun PMB", "Data diri", "Rapor/ijazah", "Identitas", "Dokumen pendukung"],
    strategy: "Gunakan skor tryout untuk menilai peluang prodi favorit dan cadangan secara realistis.",
    sourceUrl: "https://pmb.unand.ac.id/",
    sourceLabel: "PMB UNAND",
  },
  {
    id: "unsri",
    name: "Universitas Sriwijaya",
    shortName: "USM UNSRI",
    selectionName: "Ujian Saringan Masuk UNSRI 2026",
    city: "Palembang/Indralaya",
    openAt: "Mei 2026",
    closeAt: "Cek portal USM",
    examAt: "Ujian saringan masuk",
    resultAt: "Cek portal USM",
    status: "Buka Segera",
    color: "bg-blue-100 text-blue-700",
    priority: "Menengah",
    fee: "Cek portal USM UNSRI",
    scheme: "Ujian saringan mandiri untuk program sarjana/diploma sesuai ketentuan kampus.",
    materials: "TPS, akademik dasar, literasi, numerasi, dan bidang sesuai kelompok prodi.",
    documents: ["Akun USM", "Identitas", "Ijazah/SKL", "Pilihan prodi", "Bukti pembayaran"],
    strategy: "Susun latihan dengan porsi penalaran dan numerasi yang seimbang.",
    sourceUrl: "https://usm.unsri.ac.id/",
    sourceLabel: "USM UNSRI",
  },
  {
    id: "unej",
    name: "Universitas Jember",
    shortName: "SEMMABA UNEJ",
    selectionName: "Seleksi Mandiri Mahasiswa Baru UNEJ 2026",
    city: "Jember",
    openAt: "Mei 2026",
    closeAt: "Cek portal PMB",
    examAt: "Tes/penilaian sesuai jalur",
    resultAt: "Cek portal PMB",
    status: "Buka Segera",
    color: "bg-blue-100 text-blue-700",
    priority: "Menengah",
    fee: "Cek portal PMB UNEJ",
    scheme: "Seleksi mandiri mahasiswa baru dengan pilihan jalur sesuai ketentuan universitas.",
    materials: "TPS, literasi, numerasi, dan penalaran akademik.",
    documents: ["Akun PMB", "Rapor/ijazah", "Identitas", "Data sekolah", "Bukti pembayaran"],
    strategy: "Pantau jadwal gelombang; jangan menunggu pengumuman kampus lain jika deadline dekat.",
    sourceUrl: "https://pmb.unej.ac.id/",
    sourceLabel: "PMB UNEJ",
  },
  {
    id: "upnvj",
    name: "UPN Veteran Jakarta",
    shortName: "SEMA UPNVJ",
    selectionName: "Seleksi Mandiri UPN Veteran Jakarta 2026",
    city: "Jakarta",
    openAt: "Mei 2026",
    closeAt: "Cek portal PENMARU",
    examAt: "Tes/UTBK/prestasi sesuai jalur",
    resultAt: "Cek portal PENMARU",
    status: "Bertahap",
    color: "bg-blue-100 text-blue-700",
    priority: "Menengah",
    fee: "Cek portal PENMARU UPNVJ",
    scheme: "Jalur mandiri untuk program sarjana dan diploma dengan skema tes atau nilai.",
    materials: "TPS, literasi, numerasi, dan kemampuan akademik sesuai prodi.",
    documents: ["Akun PENMARU", "Identitas", "Ijazah/SKL", "Skor UTBK bila digunakan", "Bukti pembayaran"],
    strategy: "Karena kampus Jakarta peminatnya padat, bandingkan peluang prodi utama dan alternatif sejak awal.",
    sourceUrl: "https://penmaru.upnvj.ac.id/",
    sourceLabel: "PENMARU UPNVJ",
  },
];
